import {createContext,useContext,useEffect,useReducer} from 'react'
import {useMutation,useQuery} from '@tanstack/react-query'
import {Navigate,useNavigate,useParams} from 'react-router-dom'
import {guestApi} from '../api/client'
import {money,statusLabel} from '../lib/format'
const CartContext=createContext(null)
export function cartReducer(s,a){if(a.type==='ADD'){const found=s.find(x=>x.id===a.item.id);return found?s.map(x=>x.id===a.item.id?{...x,quantity:x.quantity+1}:x):[...s,{...a.item,quantity:1}]}if(a.type==='DEC')return s.map(x=>x.id===a.id?{...x,quantity:x.quantity-1}:x).filter(x=>x.quantity>0);if(a.type==='CLEAR')return [];return s}
function CartProvider({token,children}){const key=`smartserve.cart.${token}`;const [cart,dispatch]=useReducer(cartReducer,[],()=>JSON.parse(sessionStorage.getItem(key)||'[]'));useEffect(()=>sessionStorage.setItem(key,JSON.stringify(cart)),[cart,key]);return <CartContext.Provider value={{cart,dispatch}}>{children}</CartContext.Provider>}
export function GuestEntry(){const {qrToken}=useParams(),q=useQuery({queryKey:['guest-session',qrToken],queryFn:()=>guestApi.session(qrToken),retry:false});if(q.isLoading)return <GuestState text="Checking your table…"/>;if(q.error)return <GuestState text={q.error.message}/>;if(!q.data.orderingEnabled)return <GuestState text="This table is not accepting new orders right now."/>;return <Navigate to={`/guest/${qrToken}/menu`} replace/>}
export function GuestMenu(){const {qrToken}=useParams();return <CartProvider token={qrToken}><GuestMenuInner token={qrToken}/></CartProvider>}
function GuestMenuInner({token}){const q=useQuery({queryKey:['guest-menu',token],queryFn:()=>guestApi.menu(token)}),{cart,dispatch}=useContext(CartContext),nav=useNavigate();if(q.isLoading)return <GuestState text="Preparing today’s menu…"/>;return <div className="guest"><header><span className="eyebrow">SMARTSERVE</span><h1>What sounds good?</h1><p>Fresh from the kitchen, ordered right from your table.</p></header><div className="guestGrid">{q.data.items.map(i=><article className="card guestItem" key={i.id}><div className="dish">{i.foodType==='VEG'?'🌿':'🍽️'}</div><div><small>{i.foodType} · {i.spiceLevel}</small><h3>{i.name}</h3><p>{i.description}</p><b>{money(i.price)}</b></div><button className="round" onClick={()=>dispatch({type:'ADD',item:i})}>+</button></article>)}</div>{cart.length>0&&<button className="cartBar" onClick={()=>nav(`/guest/${token}/checkout`,{state:{cart}})}><span>{cart.reduce((n,x)=>n+x.quantity,0)} items</span><b>Review order · {money(cart.reduce((n,x)=>n+x.price*x.quantity,0))}</b></button>}</div>}
export function GuestCheckout(){const {qrToken}=useParams(),nav=useNavigate(),cart=history.state?.usr?.cart||[];const mutation=useMutation({mutationFn:data=>guestApi.order(qrToken,data),onSuccess:r=>{sessionStorage.removeItem(`smartserve.cart.${qrToken}`);nav(`/guest/order/${r.trackingToken}`,{replace:true})}});if(!cart.length)return <Navigate to={`/guest/${qrToken}/menu`} replace/>;return <div className="guest checkout"><button className="back" onClick={()=>nav(-1)}>← Back to menu</button><h1>Almost there</h1><div className="card"><h3>Your order</h3>{cart.map(i=><div className="line" key={i.id}><span>{i.quantity}× {i.name}</span><b>{money(i.quantity*i.price)}</b></div>)}</div><form className="card" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({customerName:f.get('name'),customerPhone:f.get('phone')||null,smsConsent:f.get('sms')==='on',specialInstructions:f.get('notes')||null,items:cart.map(i=>({menuItemId:i.id,quantity:i.quantity}))})}}><label>Your name<input name="name" required maxLength="100"/></label><label>Phone (optional)<input name="phone" placeholder="+91…"/></label><label>Kitchen note<textarea name="notes" maxLength="500"/></label><label className="check"><input type="checkbox" name="sms"/> Send me SMS updates about this order</label>{mutation.error&&<div className="alert">{mutation.error.message}</div>}<button className="primary" disabled={mutation.isPending}>{mutation.isPending?'Placing order…':`Place order · ${money(cart.reduce((n,x)=>n+x.price*x.quantity,0))}`}</button></form></div>}
export function GuestTracking(){const {trackingToken}=useParams(),q=useQuery({queryKey:['track',trackingToken],queryFn:()=>guestApi.track(trackingToken),refetchInterval:data=>['SERVED','CANCELLED'].includes(data.state.data?.orderStatus)?false:5000});if(q.isLoading)return <GuestState text="Finding your order…"/>;if(q.error)return <GuestState text={q.error.message}/>;const o=q.data;return <div className="guest tracking"><div className="logo">SS</div><span className="eyebrow">ORDER #{o.id}</span><h1>{statusLabel[o.orderStatus]}</h1><p>{o.orderStatus==='READY'?'Your food is ready—your server will bring it shortly.':'This page updates automatically.'}</p><div className="steps">{['PENDING','PREPARING','READY','SERVED'].map((s,i)=><div className={i<=['PENDING','PREPARING','READY','SERVED'].indexOf(o.orderStatus)?'done':''} key={s}><i/><span>{statusLabel[s]}</span></div>)}</div><div className="card"><h3>Order summary</h3>{o.items.map(i=><div className="line" key={i.id}><span>{i.quantity}× {i.itemName}</span><b>{money(i.lineTotal)}</b></div>)}<div className="line total"><span>Total</span><b>{money(o.totalAmount)}</b></div></div></div>}
function GuestState({text}){return <main className="center guestState"><div className="logo">SS</div><div className="spinner"/><h2>{text}</h2></main>}
