-- ============================================================
-- 1. RESTAURANTS
-- Root table for the restaurant hierarchy.
-- ============================================================

CREATE TABLE restaurants (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(120) NOT NULL UNIQUE,
                             owner_name VARCHAR(120) NOT NULL,
                             active BOOLEAN NOT NULL,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);


-- ============================================================
-- 2. BRANCHES
-- Depends on restaurants.
-- ============================================================

CREATE TABLE branches (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          restaurant_id BIGINT NOT NULL,
                          name VARCHAR(120) NOT NULL,
                          address VARCHAR(300) NOT NULL,
                          phone VARCHAR(20) NOT NULL,
                          active BOOLEAN NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                          updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                          CONSTRAINT fk_branches_restaurant
                              FOREIGN KEY (restaurant_id)
                                  REFERENCES restaurants(id),

                          CONSTRAINT uk_branch_restaurant_name
                              UNIQUE (restaurant_id, name)
);


-- ============================================================
-- 3. RESTAURANT TABLES
-- Depends on branches.
-- ============================================================

CREATE TABLE restaurant_tables (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   branch_id BIGINT NOT NULL,
                                   table_number VARCHAR(20) NOT NULL,
                                   capacity INTEGER NOT NULL,
                                   status VARCHAR(30) NOT NULL,
                                   qr_token VARCHAR(64) UNIQUE,
                                   created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                   updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                                   CONSTRAINT fk_restaurant_tables_branch
                                       FOREIGN KEY (branch_id)
                                           REFERENCES branches(id),

                                   CONSTRAINT uk_branch_table_number
                                       UNIQUE (branch_id, table_number)
);


-- ============================================================
-- 4. USERS
-- Depends on branches, although branch assignment is optional.
-- ============================================================

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       full_name VARCHAR(100) NOT NULL,
                       role VARCHAR(30) NOT NULL,
                       active BOOLEAN NOT NULL,
                       branch_id BIGINT,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                       CONSTRAINT fk_users_branch
                           FOREIGN KEY (branch_id)
                               REFERENCES branches(id)
);


-- ============================================================
-- 5. MENU CATEGORIES
-- Independent root of the menu hierarchy.
-- ============================================================

CREATE TABLE menu_categories (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(100) NOT NULL UNIQUE,
                                 description VARCHAR(500),
                                 display_order INTEGER NOT NULL,
                                 active BOOLEAN NOT NULL,
                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);


-- ============================================================
-- 6. MENU ITEMS
-- Depends on menu_categories.
-- ============================================================

CREATE TABLE menu_items (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            description VARCHAR(150),
                            price NUMERIC(10, 2) NOT NULL,
                            category_id BIGINT NOT NULL,
                            available BOOLEAN NOT NULL,
                            preparation_time_minutes INTEGER NOT NULL,
                            image_url VARCHAR(500),
                            food_type VARCHAR(30) NOT NULL,
                            spice_level VARCHAR(30) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                            CONSTRAINT fk_menu_items_category
                                FOREIGN KEY (category_id)
                                    REFERENCES menu_categories(id)
);


-- ============================================================
-- 7. CUSTOMER ORDERS
-- Depends on branches and restaurant_tables.
-- ============================================================

CREATE TABLE customer_orders (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 customer_name VARCHAR(100) NOT NULL,
                                 order_type VARCHAR(20) NOT NULL,
                                 customer_phone VARCHAR(20),
                                 sms_consent BOOLEAN NOT NULL,

                                 branch_id BIGINT NOT NULL,
                                 table_id BIGINT,

                                 order_status VARCHAR(30) NOT NULL,
                                 payment_status VARCHAR(30) NOT NULL,
                                 payment_method VARCHAR(30) NOT NULL,

                                 razorpay_order_id VARCHAR(100),
                                 razorpay_payment_id VARCHAR(100),
                                 razorpay_signature VARCHAR(255),
                                 paid_at TIMESTAMP WITH TIME ZONE,
                                 payment_failure_reason VARCHAR(500),

                                 total_amount NUMERIC(10, 2) NOT NULL,
                                 special_instructions VARCHAR(500),

                                 preparation_started_at TIMESTAMP WITH TIME ZONE,
                                 ready_at TIMESTAMP WITH TIME ZONE,

                                 tracking_token VARCHAR(64) UNIQUE,
                                 version BIGINT,

                                 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                 updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                                 CONSTRAINT fk_customer_orders_branch
                                     FOREIGN KEY (branch_id)
                                         REFERENCES branches(id),

                                 CONSTRAINT fk_customer_orders_table
                                     FOREIGN KEY (table_id)
                                         REFERENCES restaurant_tables(id)
);

CREATE INDEX idx_orders_branch_status_created
    ON customer_orders (branch_id, order_status, created_at);

CREATE INDEX idx_orders_branch_updated
    ON customer_orders (branch_id, updated_at);


-- ============================================================
-- 8. ORDER ITEMS
-- Depends on customer_orders and menu_items.
-- ============================================================

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             menu_item_id BIGINT NOT NULL,
                             item_name VARCHAR(100) NOT NULL,
                             quantity INTEGER NOT NULL,
                             unit_price NUMERIC(10, 2) NOT NULL,
                             line_total NUMERIC(10, 2) NOT NULL,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                             CONSTRAINT fk_order_items_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES customer_orders(id),

                             CONSTRAINT fk_order_items_menu_item
                                 FOREIGN KEY (menu_item_id)
                                     REFERENCES menu_items(id)
);


-- ============================================================
-- 9. NOTIFICATIONS
-- Depends on branches, customer_orders, and users.
-- ============================================================

CREATE TABLE notifications (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               branch_id BIGINT,
                               order_id BIGINT,
                               recipient_user_id BIGINT,
                               recipient_phone VARCHAR(20),

                               channel VARCHAR(30) NOT NULL,
                               type VARCHAR(40) NOT NULL,
                               title VARCHAR(160) NOT NULL,
                               message VARCHAR(1000) NOT NULL,
                               status VARCHAR(30) NOT NULL,

                               error_message VARCHAR(1000),
                               sent_at TIMESTAMP WITH TIME ZONE,
                               read_at TIMESTAMP WITH TIME ZONE,

                               created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                               CONSTRAINT fk_notifications_branch
                                   FOREIGN KEY (branch_id)
                                       REFERENCES branches(id),

                               CONSTRAINT fk_notifications_order
                                   FOREIGN KEY (order_id)
                                       REFERENCES customer_orders(id),

                               CONSTRAINT fk_notifications_recipient_user
                                   FOREIGN KEY (recipient_user_id)
                                       REFERENCES users(id)
);
